# permissions for end users to edit qdrantclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: qdrant-operator
    app.kubernetes.io/managed-by: kustomize
  name: qdrantcluster-editor-role
rules:
- apiGroups:
  - qdrant.qdrantoperator.io
  resources:
  - qdrantclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qdrant.qdrantoperator.io
  resources:
  - qdrantclusters/status
  verbs:
  - get
