---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - qdrant.qdrantoperator.io
  resources:
  - qdrantclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qdrant.qdrantoperator.io
  resources:
  - qdrantclusters/finalizers
  verbs:
  - update
- apiGroups:
  - qdrant.qdrantoperator.io
  resources:
  - qdrantclusters/status
  verbs:
  - get
  - patch
  - update
