apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: qdrant-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qdrant-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qdrant-operator
subjects:
- kind: ServiceAccount
  name: qdrant-operator
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qdrant-operator
rules:
# Allow to watch & edit statefulsets
- apiGroups: ["qdrant.qdrantoperator.io"]
  resources: ["qdrantclusters", "qdrantclusters/status"]
  verbs: ["get", "list", "watch", "patch", "delete", "post", "create", "update"]
#   , "configmaps", "services", "poddisruptionbudgets"
- apiGroups: [""]
  resources: ["services", "configmaps", "pods"]
  verbs: ["get", "list", "watch", "patch", "delete", "post", "create", "update"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "patch", "delete", "post", "create", "update"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "patch", "delete", "post", "create", "update"]
