name: Build and push Chart

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Mokto
          password: ${{ secrets.PERSONAL_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/mokto/qdrant-operator:latest,ghcr.io/mokto/qdrant-operator:${{ github.ref_name }}

      
  build-push:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          path: 'main'

      - uses: actions/checkout@v4
        with:
          path: 'gh-pages'

      - run: |
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git checkout gh-pages

      - name: Build qdrant-operator chart
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm package -u main/charts/qdrant-operator --destination gh-pages/charts

      - name: Build chart
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm repo index --url https://mokto.github.io/qdrant-operator ./gh-pages/charts

      - name: Commit files
        run: |
          cd gh-pages
          git add .
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@9870d48124da805820c70ebc6ba563c715551019
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./gh-pages/charts
        with:
          keepFiles: true
